language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - REQUIREMENTS=travis_wtf1.txt
  - REQUIREMENTS=travis_wtf2.txt

install: 
 - "pip install -r $REQUIREMENTS --use-mirrors"
  - pip install coveralls
services: mongodb

script:
 - nosetests flask_admin/tests
 - coverage run --source=flask-admin setup.py test

after_success:
 - coveralls
